### ISSUE TITLE
Ta bort Slack-tråd när man tar bort awards

### ISSUE THREAD

**Issue by niclaslindstedt** [Etimo/etimo-achievements#417]
Om man tar bort en award i appen så borde den tas bort från Slack också.

Vi kommer behöva spara slack thread id i awards-tabellen för att kunna göra detta.

**Comment by elmaxe** [comment]
Ska vi ha någon webhook då som slack skickar en request till när man tar bort ett meddelande med meddelande-id?

**Comment by elmaxe** [comment]
Detta betyder att vi kommer skapa awarden efter vi skickat slackmeddelandet. Alternativt att vi skapar awarden, skickar slackmeddelande och sedan uppdaterar awarden med tråd-id
